Add /bigobj compile option to MSVC build (#7228)
When targeting arm64 Debug, this error is detected:
`libclang\dxcrewriteunused.cpp(1,1): error C1128: number of sections
exceeded object file format limit: compile with /bigobj`
This PR adds a compile option for the folder that contains
dxcrewriteunused.cpp, so that the limit on the number of sections is
increased, and compilation may succeed.