[Internal] Remove dead fallthrough statement (#7433)
This PR removes a dead fallthrough statement after a switch-statement's
case that is terminated by a break;
This needs to be removed, because the way linux builds dxc in our
internal infrastructure, it errors when a dead fallthrough statement is
detected.
For context, here is the relevant error:

```
ScalarReplAggregatesHLSL.cpp:2822:9: error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
        LLVM_FALLTHROUGH;
        ^
... DXC/include/llvm/Support/Compiler.h:224:26: note: expanded from macro 'LLVM_FALLTHROUGH'
#define LLVM_FALLTHROUGH [[fallthrough]]
                         ^
1 error generated.
```