[NFC] Fix TAEF string literals in HLSL exec tests (#9004)
Several strings passed to TAEF were not wide strings and caused build
failures on some machines for the HLSL exec tests depending on the
version of TAEF headers used.

```
| [1505/1716] Building CXX object tools\clang\unittests\HLSLExec\CMakeFiles\ExecHLSLTests.dir\LongVectors.cpp.obj
| FAILED: [code=2] tools/clang/unittests/HLSLExec/CMakeFiles/ExecHLSLTests.dir/LongVectors.cpp.obj
| "C:\Program Files\WinGet\Links\sccache.exe" C:\PROGRA~1\MICROS~1\18\COMMUN~1\VC\Tools\MSVC\1451~1.362\bin\HOSTAR~1\arm64\cl.exe  /nologo /TP -DENABLE_SPIRV_CODEGEN -DMSFT_SUPPORTS_CHILD_PROCESSES -DSUPPORT_QUERY_GIT_COMMIT_INFO -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_GNU_SOURCE -D_ITERATOR_DEBUG_LEVEL=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\build\tools\clang\unittests\HLSLExec -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\tools\clang\unittests\HLSLExec -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\tools\clang\include -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\build\tools\clang\include -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\include\llvm\llvm_assert -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\build\include -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\include -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\build\include\dxc\Tracing -I\directx -I\wsl\stubs -I"C:\Program Files (x86)\Windows Kits\10\Testing\Development\inc" -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um" -I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\shared" -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\include\dxc\Test -IC:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\include\dxc\Support /DWIN32 /D_WINDOWS   -wd4180 -wd4244 -wd4258 -wd4267 -wd4291 -wd4345 -wd4351 -wd4355 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4800 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4324 -we4238 /W4 /Zc:sizedDealloc- /bigobj /O2 /Ob1  -std:c++17 -MD -Z7   -UNDEBUG /EHsc /guard:cf /showIncludes /Fotools\clang\unittests\HLSLExec\CMakeFiles\ExecHLSLTests.dir\LongVectors.cpp.obj /Fdtools\clang\unittests\HLSLExec\CMakeFiles\ExecHLSLTests.dir\ /FS -c C:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\tools\clang\unittests\HLSLExec\LongVectors.cpp
| C:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\tools\clang\unittests\HLSLExec\LongVectorTestData.h(61): error C2664: 'bool WEX::TestExecution::Private::MacroVerify::Fail(const WEX::TestExecution::ErrorInfo &,const wchar_t *)': cannot convert argument 2 from 'const char [18]' to 'const wchar_t *'
| C:\Users\Admin\.cache\act\771c49b93e7b4b67\hostexecutor\DXC\tools\clang\unittests\HLSLExec\LongVectorTestData.h(61): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
| C:\Program Files (x86)\Windows Kits\10\Testing\Development\inc\Verify.h(1788): note: see declaration of 'WEX::TestExecution::Private::MacroVerify::Fail'
```