Remove LLVM_C_FALLTHROUGH instances that cause warnings on clang-12 (#6134)
The clang-12 warning is:

error: fallthrough annotation in unreachable code
[-Werror,-Wimplicit-fallthrough]

These LLVM_C_FALLTHROUGH were originally added to silence GCC warnings,
but the GCC PR validation build is has succeeded, so it looks like they
are not needed.

(cherry picked from commit eb4cec4ad16e0a0d458f274a670d514f976bb59b)