[SPIR-V] Omit BufferBlock on SPIR-V 1.4 (~ Vulkan 1.1) instead of Vulkan 1.2 (#4370)
According to the SPIR-V validator this annotation was last usable on
SPIR-V 1.3:

    fatal error: generated SPIR-V is invalid: 2nd operand of Decorate: operand BufferBlock(3) requires SPIR-V version 1.3 or earlier
        OpDecorate %type_ByteAddressBuffer BufferBlock

    note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

The visitor was originally built to remove/omit it on Vulkan 1.2 and
higher only, but since supporting Vulkan 1.1 with SPIR-V 1.4 (in #4364)
- which conveniently sits inbetween SPIR-V 1.3 and Vulkan 1.2 - the
check must be made more stict and apply from SPIR-V 1.4 universal
onwards.