[NFC]: Rename a template parameter conflict with CALLBACK macro
This imports upstream commit
https://github.com/llvm/llvm-project/commit/54bff1522fc863329894d875d54c2fe4cd1b4f3f

This fixes the following compiler error with clang 18.1.8 with mingw-w64 toolchain.

CFG.h:916:22: error: expected a qualified name after 'typename'
  916 |   template <typename CALLBACK>
      |                      ^
minwindef.h:90:18: note: expanded from macro 'CALLBACK'
   90 | #define CALLBACK __stdcall
      |                  ^