Remove LLVM_C_FALLTHROUGH that cause warnings on clang-12
The clang-12 warning is:

error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]